services:
  - type: web
    name: ielts-anime-novel
    env: static
    buildCommand: npm run build:ui
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
